// Generated by scripts/generate-widget-contract.mjs. Do not edit.

import Foundation

public enum RenderWidgetContract {
    public static let version = 1
    public static let nodeKinds: Set<String> = ["column", "row", "stack", "box", "glassPanel", "mediaCard", "scrollView", "spacer", "divider", "text", "textField", "textEditor", "dateTime", "dateTimePicker", "toggle", "timer", "taskList", "shape", "icon", "image", "button", "gauge", "progress", "grid", "list", "visualizer", "youtubePlayer"]
    public static let capabilities: Set<String> = ["network", "filesystem.read", "filesystem.write"]
    public static let anchorCorners: Set<String> = ["top-left", "top-right", "bottom-left", "bottom-right"]
    public static let themes: Set<String> = ["dark-glass", "light", "monochrome", "retro"]
    public static let providers: Set<String> = ["system.cpu", "system.memory", "system.time", "spotify.account", "spotify.track.title", "spotify.track.artist", "spotify.playback.isPlaying", "spotify.playback.progress", "spotify.playback.volume", "reminders.account", "reminders.items", "reminders.incompleteCount", "reminders.next.title", "reminders.next.dueDate"]
    public static let actions: Set<String> = ["widget.refresh", "widget.reload", "spotify.play", "spotify.pause", "spotify.next", "spotify.previous", "spotify.set-volume", "reminders.create", "reminders.update", "reminders.complete", "reminders.delete"]
    public static let connectors: Set<String> = ["spotify", "reminders"]
    public static let connectorScopes: [String: Set<String>] = ["spotify": ["user-read-private", "user-read-playback-state", "user-read-currently-playing", "user-modify-playback-state"], "reminders": ["reminders.read", "reminders.write"]]
}
