// Generated by scripts/generate-widget-contract.mjs. Do not edit.

export const RENDER_WIDGET_CONTRACT_VERSION = 1 as const;
export const RENDER_WORKER_PROTOCOL_VERSION = 1 as const;
export const WIDGET_WORKER_MESSAGE_KINDS = [
  "hello",
  "helloAck",
  "ready",
  "render",
  "failure",
  "shutdown"
] as const;
export type WorkerMessageKind = typeof WIDGET_WORKER_MESSAGE_KINDS[number];
export const WIDGET_NODE_KINDS = [
  "column",
  "row",
  "stack",
  "box",
  "glassPanel",
  "mediaCard",
  "scrollView",
  "spacer",
  "divider",
  "text",
  "textField",
  "textArea",
  "textEditor",
  "dateTime",
  "dateTimePicker",
  "toggle",
  "timer",
  "taskList",
  "shape",
  "icon",
  "image",
  "button",
  "slider",
  "countdown",
  "gauge",
  "progress",
  "segmentedProgress",
  "spectrum",
  "grid",
  "gradient",
  "texture",
  "clip",
  "transform",
  "list",
  "visualizer",
  "youtubePlayer"
] as const;
export type WidgetNodeKind = typeof WIDGET_NODE_KINDS[number];
export const WIDGET_CAPABILITIES = [
  "network",
  "filesystem.read",
  "filesystem.write"
] as const;
export type WidgetCapability = typeof WIDGET_CAPABILITIES[number];
export const WIDGET_ANCHOR_CORNERS = [
  "top-left",
  "top-right",
  "bottom-left",
  "bottom-right"
] as const;
export type WidgetAnchorCorner = typeof WIDGET_ANCHOR_CORNERS[number];
export const WIDGET_THEME_NAMES = [
  "dark-glass",
  "light",
  "monochrome",
  "retro"
] as const;
export type WidgetThemeName = typeof WIDGET_THEME_NAMES[number];
export const WIDGET_PROVIDER_NAMES = [
  "system.cpu",
  "system.memory",
  "system.time",
  "spotify.account",
  "spotify.track.title",
  "spotify.track.artist",
  "spotify.playback.isPlaying",
  "spotify.playback.progress",
  "spotify.playback.volume",
  "reminders.account",
  "reminders.items",
  "reminders.incompleteCount",
  "reminders.next.title",
  "reminders.next.dueDate"
] as const;
export type WidgetProviderName = typeof WIDGET_PROVIDER_NAMES[number];
export const WIDGET_ACTION_NAMES = [
  "widget.refresh",
  "widget.reload",
  "spotify.play",
  "spotify.pause",
  "spotify.next",
  "spotify.previous",
  "spotify.set-volume",
  "reminders.create",
  "reminders.update",
  "reminders.complete",
  "reminders.delete"
] as const;
export type WidgetActionName = typeof WIDGET_ACTION_NAMES[number];
export const WIDGET_CONNECTOR_NAMES = [
  "spotify",
  "reminders"
] as const;
export type WidgetConnectorName = typeof WIDGET_CONNECTOR_NAMES[number];
export const WIDGET_CONNECTOR_SCOPES = {
  "spotify": [
    "user-read-private",
    "user-read-playback-state",
    "user-read-currently-playing",
    "user-modify-playback-state"
  ],
  "reminders": [
    "reminders.read",
    "reminders.write"
  ]
} as const;
export const WIDGET_PROVIDER_CONNECTORS = {
  "spotify.account": "spotify",
  "spotify.track.title": "spotify",
  "spotify.track.artist": "spotify",
  "spotify.playback.isPlaying": "spotify",
  "spotify.playback.progress": "spotify",
  "spotify.playback.volume": "spotify",
  "reminders.account": "reminders",
  "reminders.items": "reminders",
  "reminders.incompleteCount": "reminders",
  "reminders.next.title": "reminders",
  "reminders.next.dueDate": "reminders"
} as const;
export const WIDGET_ACTION_CONNECTORS = {
  "spotify.play": "spotify",
  "spotify.pause": "spotify",
  "spotify.next": "spotify",
  "spotify.previous": "spotify",
  "spotify.set-volume": "spotify",
  "reminders.create": "reminders",
  "reminders.update": "reminders",
  "reminders.complete": "reminders",
  "reminders.delete": "reminders"
} as const;
export const WIDGET_CONTRACT_CATALOG = [
  {
    "name": "Column",
    "wireName": "column",
    "kind": "primitive",
    "summary": "Vertical layout container"
  },
  {
    "name": "Row",
    "wireName": "row",
    "kind": "primitive",
    "summary": "Horizontal layout container"
  },
  {
    "name": "Stack",
    "wireName": "stack",
    "kind": "primitive",
    "summary": "Layered layout container"
  },
  {
    "name": "Box",
    "wireName": "box",
    "kind": "primitive",
    "summary": "General styled container"
  },
  {
    "name": "GlassPanel",
    "wireName": "glassPanel",
    "kind": "primitive",
    "summary": "Theme-aware glass material panel"
  },
  {
    "name": "MediaCard",
    "wireName": "mediaCard",
    "kind": "primitive",
    "summary": "Theme-aware media surface"
  },
  {
    "name": "ScrollView",
    "wireName": "scrollView",
    "kind": "primitive",
    "summary": "Native scrollable content container"
  },
  {
    "name": "Spacer",
    "wireName": "spacer",
    "kind": "primitive",
    "summary": "Fixed or flexible empty space"
  },
  {
    "name": "Divider",
    "wireName": "divider",
    "kind": "primitive",
    "summary": "Horizontal or vertical separator"
  },
  {
    "name": "Text",
    "wireName": "text",
    "kind": "primitive",
    "summary": "Rendered text or provider value"
  },
  {
    "name": "TextField",
    "wireName": "textField",
    "kind": "primitive",
    "summary": "Editable single-line text control"
  },
  {
    "name": "TextArea",
    "wireName": "textArea",
    "kind": "primitive",
    "summary": "Editable multi-line text control with Widget state binding"
  },
  {
    "name": "TextEditor",
    "wireName": "textEditor",
    "kind": "primitive",
    "summary": "Editable multi-line text control"
  },
  {
    "name": "DateTime",
    "wireName": "dateTime",
    "kind": "primitive",
    "summary": "Formatted date or time value"
  },
  {
    "name": "DateTimePicker",
    "wireName": "dateTimePicker",
    "kind": "primitive",
    "summary": "Native date and time picker"
  },
  {
    "name": "Toggle",
    "wireName": "toggle",
    "kind": "primitive",
    "summary": "Boolean control"
  },
  {
    "name": "Timer",
    "wireName": "timer",
    "kind": "primitive",
    "summary": "Persistent countdown timer"
  },
  {
    "name": "TaskList",
    "wireName": "taskList",
    "kind": "primitive",
    "summary": "Editable persistent task list"
  },
  {
    "name": "Shape",
    "wireName": "shape",
    "kind": "primitive",
    "summary": "Native geometric shape"
  },
  {
    "name": "Icon",
    "wireName": "icon",
    "kind": "primitive",
    "summary": "Native symbol icon"
  },
  {
    "name": "Image",
    "wireName": "image",
    "kind": "primitive",
    "summary": "Asset, URL, or provider-backed image"
  },
  {
    "name": "Button",
    "wireName": "button",
    "kind": "primitive",
    "summary": "Native action control"
  },
  {
    "name": "Slider",
    "wireName": "slider",
    "kind": "primitive",
    "summary": "Persistent bounded numeric control"
  },
  {
    "name": "Countdown",
    "wireName": "countdown",
    "kind": "primitive",
    "summary": "User-adjustable persistent countdown"
  },
  {
    "name": "Gauge",
    "wireName": "gauge",
    "kind": "primitive",
    "summary": "Bounded value gauge"
  },
  {
    "name": "Progress",
    "wireName": "progress",
    "kind": "primitive",
    "summary": "Bounded progress indicator"
  },
  {
    "name": "SegmentedProgress",
    "wireName": "segmentedProgress",
    "kind": "primitive",
    "summary": "Discrete segmented progress indicator"
  },
  {
    "name": "Spectrum",
    "wireName": "spectrum",
    "kind": "primitive",
    "summary": "Finite numeric spectrum visualization"
  },
  {
    "name": "Grid",
    "wireName": "grid",
    "kind": "primitive",
    "summary": "Column-based layout container"
  },
  {
    "name": "Gradient",
    "wireName": "gradient",
    "kind": "primitive",
    "summary": "Native gradient container"
  },
  {
    "name": "Texture",
    "wireName": "texture",
    "kind": "primitive",
    "summary": "Built-in or asset texture surface"
  },
  {
    "name": "Clip",
    "wireName": "clip",
    "kind": "primitive",
    "summary": "Native clipping container"
  },
  {
    "name": "Transform",
    "wireName": "transform",
    "kind": "primitive",
    "summary": "Native transformed container"
  },
  {
    "name": "List",
    "wireName": "list",
    "kind": "primitive",
    "summary": "Static or provider-backed list"
  },
  {
    "name": "Visualizer",
    "wireName": "visualizer",
    "kind": "primitive",
    "summary": "Provider-backed visualizer surface"
  },
  {
    "name": "YouTubePlayer",
    "wireName": "youtubePlayer",
    "kind": "primitive",
    "summary": "Native YouTube playback surface"
  },
  {
    "name": "system.cpu",
    "kind": "provider",
    "summary": "Current CPU utilization"
  },
  {
    "name": "system.memory",
    "kind": "provider",
    "summary": "Current memory utilization"
  },
  {
    "name": "system.time",
    "kind": "provider",
    "summary": "Current local time"
  },
  {
    "name": "spotify.account",
    "kind": "provider",
    "summary": "Spotify account availability"
  },
  {
    "name": "spotify.track.title",
    "kind": "provider",
    "summary": "Current Spotify track title"
  },
  {
    "name": "spotify.track.artist",
    "kind": "provider",
    "summary": "Current Spotify track artist"
  },
  {
    "name": "spotify.playback.isPlaying",
    "kind": "provider",
    "summary": "Spotify playback state"
  },
  {
    "name": "spotify.playback.progress",
    "kind": "provider",
    "summary": "Spotify playback progress"
  },
  {
    "name": "spotify.playback.volume",
    "kind": "provider",
    "summary": "Spotify playback volume"
  },
  {
    "name": "reminders.account",
    "kind": "provider",
    "summary": "macOS Reminders account availability"
  },
  {
    "name": "reminders.items",
    "kind": "provider",
    "summary": "macOS Reminders items"
  },
  {
    "name": "reminders.incompleteCount",
    "kind": "provider",
    "summary": "Incomplete Reminders count"
  },
  {
    "name": "reminders.next.title",
    "kind": "provider",
    "summary": "Next incomplete Reminder title"
  },
  {
    "name": "reminders.next.dueDate",
    "kind": "provider",
    "summary": "Next incomplete Reminder due date"
  },
  {
    "name": "widget.refresh",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Request a Widget refresh"
  },
  {
    "name": "widget.reload",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Request a Widget reload"
  },
  {
    "name": "spotify.play",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Start Spotify playback"
  },
  {
    "name": "spotify.pause",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Pause Spotify playback"
  },
  {
    "name": "spotify.next",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Skip to the next Spotify track"
  },
  {
    "name": "spotify.previous",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Return to the previous Spotify track"
  },
  {
    "name": "spotify.set-volume",
    "kind": "action",
    "actionKind": "set",
    "summary": "Set Spotify volume from 0 to 100"
  },
  {
    "name": "reminders.create",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Create a macOS Reminder"
  },
  {
    "name": "reminders.update",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Update a macOS Reminder"
  },
  {
    "name": "reminders.complete",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Complete or reopen a macOS Reminder"
  },
  {
    "name": "reminders.delete",
    "kind": "action",
    "actionKind": "invoke",
    "summary": "Delete a macOS Reminder"
  },
  {
    "name": "spotify",
    "kind": "connector",
    "summary": "spotify host-owned connector"
  },
  {
    "name": "reminders",
    "kind": "connector",
    "summary": "reminders host-owned connector"
  },
  {
    "name": "network",
    "kind": "capability",
    "summary": "Declared network capability"
  },
  {
    "name": "filesystem.read",
    "kind": "capability",
    "summary": "Declared filesystem.read capability"
  },
  {
    "name": "filesystem.write",
    "kind": "capability",
    "summary": "Declared filesystem.write capability"
  }
] as const;

export type WidgetLengthContract = number | "fill" | "fit" | "auto" | {
  unit: "percent" | "fraction";
  value: number;
};

export type WidgetSpacingContract = number | {
  horizontal?: number;
  vertical?: number;
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
};

export type WidgetCornerRadiiContract = {
  topLeft?: number;
  topRight?: number;
  bottomRight?: number;
  bottomLeft?: number;
};

export type WidgetBorderContract = {
  color?: string;
  width?: number;
  radius?: number;
};

export type WidgetShadowContract = {
  color?: string;
  radius?: number;
  x?: number;
  y?: number;
  opacity?: number;
  kind?: "outset" | "inset" | "text";
};

export type WidgetFontContract = {
  family?: string;
  size?: number;
  weight?: "regular" | "medium" | "semibold" | "bold";
  monospace?: boolean;
  leading?: number;
  tracking?: number;
  alignment?: "leading" | "center" | "trailing" | "justified";
  lineLimit?: number;
  tabularNumbers?: boolean;
  truncation?: "head" | "middle" | "tail" | "clip";
};

export type WidgetInteractionAppearanceContract = {
  color?: string;
  backgroundColor?: string;
  opacity?: number;
  borderColor?: string;
  shadow?: WidgetShadowContract;
  scale?: number;
};

export type WidgetInteractionStyleContract = {
  cursor?: "default" | "pointer" | "text" | "crosshair" | "move" | "not-allowed";
  hover?: WidgetInteractionAppearanceContract;
  pressed?: WidgetInteractionAppearanceContract;
  focus?: WidgetInteractionAppearanceContract;
  disabled?: WidgetInteractionAppearanceContract;
};

export type WidgetStyleContract = {
  width?: WidgetLengthContract;
  height?: WidgetLengthContract;
  minWidth?: WidgetLengthContract;
  maxWidth?: WidgetLengthContract;
  minHeight?: WidgetLengthContract;
  maxHeight?: WidgetLengthContract;
  aspectRatio?: number;
  color?: string;
  backgroundColor?: string;
  opacity?: number;
  padding?: WidgetSpacingContract;
  margin?: WidgetSpacingContract;
  gap?: number;
  alignItems?: "leading" | "center" | "trailing" | "top" | "bottom" | "fill" | "space-between";
  justifyContent?: "leading" | "center" | "trailing" | "top" | "bottom" | "fill" | "space-between";
  alignSelf?: "leading" | "center" | "trailing" | "top" | "bottom" | "fill" | "space-between";
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: WidgetLengthContract;
  flexWrap?: "nowrap" | "wrap";
  radius?: number | WidgetCornerRadiiContract;
  border?: WidgetBorderContract;
  shadow?: WidgetShadowContract;
  shadows?: WidgetShadowContract[];
  font?: WidgetFontContract;
  overflow?: "visible" | "hidden" | "clip";
  interaction?: WidgetInteractionStyleContract;
  material?: "solid" | "thin" | "thick";
  role?: "surface" | "panel" | "control" | "status" | "media";
  density?: "compact" | "comfortable";
  tokens?: ("surface" | "surface.elevated" | "surface.panel" | "surface.control" | "surface.status" | "text.primary" | "text.secondary" | "text.tertiary" | "border.subtle" | "accent" | "accent.muted" | "danger" | "success" | "mono")[];
};

export type ImageSourceContract = {
  kind: "asset";
  name: string;
} | {
  kind: "url";
  url: string;
} | {
  kind: "provider";
  name: string;
};

export type WidgetTextureSourceContract = {
  kind: "builtin";
  name: "grain" | "grid";
} | {
  kind: "asset";
  name: string;
};

export type WidgetImageOptionsContract = {
  fit?: "contain" | "cover" | "fill";
  repeat?: "none" | "x" | "y" | "both";
  position?: "leading" | "center" | "trailing";
  tint?: string;
};

export type WidgetGradientStopContract = {
  color: string;
  position: number;
};

export type WidgetTransformContract = {
  rotation?: number;
  scale?: number;
  offsetX?: number;
  offsetY?: number;
};

export type WidgetAnimationContract = {
  property: "opacity" | "rotation" | "scale" | "offsetX" | "offsetY";
  from: number;
  to: number;
  duration: number;
  delay?: number;
  repeat?: number | "forever";
  easing?: "linear" | "ease-in" | "ease-out" | "ease-in-out";
};

export type WidgetStateReferenceContract = {
  key: string;
  initial: string | number | boolean;
};

export type WidgetActionContract = {
  type: "invoke";
  name: "widget.refresh" | "widget.reload" | "spotify.play" | "spotify.pause" | "spotify.next" | "spotify.previous" | "reminders.create" | "reminders.update" | "reminders.complete" | "reminders.delete";
  payload?: WidgetJSONValueContract;
} | {
  type: "set";
  name: "spotify.set-volume";
  value: number;
};

export type WidgetTaskItemContract = {
  id: string;
  text: string;
  completed?: boolean;
};

export type WidgetListItemContract = {
  id: string;
  title: string;
  subtitle?: string;
  completed?: boolean;
};

export type WidgetNodeContract = {
  kind: "column" | "row" | "stack" | "box" | "glassPanel" | "mediaCard" | "scrollView" | "spacer" | "divider" | "text" | "textField" | "textArea" | "textEditor" | "dateTime" | "dateTimePicker" | "toggle" | "timer" | "taskList" | "shape" | "icon" | "image" | "button" | "slider" | "countdown" | "gauge" | "progress" | "segmentedProgress" | "spectrum" | "grid" | "gradient" | "texture" | "clip" | "transform" | "list" | "visualizer" | "youtubePlayer";
  key?: string | number;
  children?: WidgetNodeContract[];
  text?: string;
  provider?: "system.cpu" | "system.memory" | "system.time" | "spotify.account" | "spotify.track.title" | "spotify.track.artist" | "spotify.playback.isPlaying" | "spotify.playback.progress" | "spotify.playback.volume" | "reminders.account" | "reminders.items" | "reminders.incompleteCount" | "reminders.next.title" | "reminders.next.dueDate";
  style?: WidgetStyleContract;
  value?: number;
  minimum?: number;
  maximum?: number;
  step?: number;
  orientation?: "horizontal" | "vertical";
  name?: string;
  source?: ImageSourceContract | WidgetTextureSourceContract;
  options?: WidgetImageOptionsContract;
  stops?: WidgetGradientStopContract[];
  direction?: string;
  transform?: WidgetTransformContract;
  animation?: WidgetAnimationContract;
  action?: WidgetActionContract;
  disabled?: boolean;
  columns?: number;
  segments?: number;
  values?: number[];
  state?: WidgetStateReferenceContract;
  durationSeconds?: number;
  tasks?: WidgetTaskItemContract[];
  items?: WidgetListItemContract[];
  videoId?: string;
  allowLinkInput?: boolean;
  autoplay?: boolean;
  controls?: boolean;
  startSeconds?: number;
  placeholder?: string;
  dateTime?: string;
  dateTimeMode?: "date" | "time" | "dateTime";
  visualizerMode?: "bars" | "waveform" | "rings";
  visualizerTempo?: number;
};

export type WidgetSizeContract = {
  width: number;
  height: number;
};

export type WidgetManifestContract = {
  schemaVersion: 1;
  name: string;
  sdkVersion: string;
  size: WidgetSizeContract;
  resizable?: boolean;
  windowShape?: "rectangle" | "circle";
  anchor: {
  corner: "top-left" | "top-right" | "bottom-left" | "bottom-right";
  offset: {
  x: number;
  y: number;
};
};
  adjustable?: {
  enabled: boolean;
  minSize?: WidgetSizeContract;
  maxSize?: WidgetSizeContract;
  responsive?: {
  modes: { [key: string]: {
  minWidth: number;
  minHeight: number;
} };
  default: string;
};
};
  capabilities: ("network" | "filesystem.read" | "filesystem.write")[];
  subscribe: ("system.cpu" | "system.memory" | "system.time" | "spotify.account" | "spotify.track.title" | "spotify.track.artist" | "spotify.playback.isPlaying" | "spotify.playback.progress" | "spotify.playback.volume" | "reminders.account" | "reminders.items" | "reminders.incompleteCount" | "reminders.next.title" | "reminders.next.dueDate")[];
  assets?: string[];
  fonts?: {
  asset: string;
  family?: string;
}[];
  accounts?: ({
  connector: "spotify" | "reminders";
  scopes: string[];
})[];
  theme?: {
  default: "dark-glass" | "light" | "monochrome" | "retro";
  options?: ("dark-glass" | "light" | "monochrome" | "retro")[];
};
};

export type WidgetJSONValueContract = string | number | boolean | null | WidgetJSONValueContract[] | { [key: string]: WidgetJSONValueContract };

export type WorkerDiagnosticContract = {
  code: string;
  path: string;
  message: string;
};

export type WorkerRenderSizeContract = {
  width: number;
  height: number;
};

export type WorkerMessageContract = {
  protocolVersion: 1;
  kind: "hello";
  messageID: string;
  workerID: string;
  supportedVersions: number[];
} | {
  protocolVersion: 1;
  kind: "helloAck";
  messageID: string;
  workerID: string;
  selectedVersion: number;
} | {
  protocolVersion: 1;
  kind: "ready";
  messageID: string;
  workerID: string;
} | {
  protocolVersion: 1;
  kind: "render";
  messageID: string;
  workerID: string;
  workspace?: string;
  sourcePath: string;
  state?: { [key: string]: WidgetJSONValueContract };
  mode?: string;
  size?: WorkerRenderSizeContract;
} | {
  protocolVersion: 1;
  kind: "render";
  messageID: string;
  workerID: string;
  tree: WidgetNodeContract;
  manifest: WidgetManifestContract;
} | {
  protocolVersion: 1;
  kind: "failure";
  messageID: string;
  workerID: string;
  diagnostics: WorkerDiagnosticContract[];
} | {
  protocolVersion: 1;
  kind: "shutdown";
  messageID: string;
  workerID: string;
};
