// Generated by scripts/generate-widget-contract.mjs. Do not edit.

export const RENDER_WIDGET_CONTRACT_VERSION = 1 as const;
export const WIDGET_NODE_KINDS = [
  "column",
  "row",
  "stack",
  "box",
  "glassPanel",
  "mediaCard",
  "scrollView",
  "spacer",
  "divider",
  "text",
  "textField",
  "textEditor",
  "dateTime",
  "dateTimePicker",
  "toggle",
  "timer",
  "taskList",
  "shape",
  "icon",
  "image",
  "button",
  "gauge",
  "progress",
  "grid",
  "list",
  "visualizer",
  "youtubePlayer"
] as const;
export const WIDGET_CAPABILITIES = [
  "network",
  "filesystem.read",
  "filesystem.write"
] as const;
export const WIDGET_ANCHOR_CORNERS = [
  "top-left",
  "top-right",
  "bottom-left",
  "bottom-right"
] as const;
export const WIDGET_THEME_NAMES = [
  "dark-glass",
  "light",
  "monochrome",
  "retro"
] as const;
export const WIDGET_PROVIDER_NAMES = [
  "system.cpu",
  "system.memory",
  "system.time",
  "spotify.account",
  "spotify.track.title",
  "spotify.track.artist",
  "spotify.playback.isPlaying",
  "spotify.playback.progress",
  "spotify.playback.volume",
  "reminders.account",
  "reminders.items",
  "reminders.incompleteCount",
  "reminders.next.title",
  "reminders.next.dueDate"
] as const;
export const WIDGET_ACTION_NAMES = [
  "widget.refresh",
  "widget.reload",
  "spotify.play",
  "spotify.pause",
  "spotify.next",
  "spotify.previous",
  "spotify.set-volume",
  "reminders.create",
  "reminders.update",
  "reminders.complete",
  "reminders.delete"
] as const;
export const WIDGET_CONNECTOR_NAMES = [
  "spotify",
  "reminders"
] as const;
export const WIDGET_CONNECTOR_SCOPES = {
  "spotify": [
    "user-read-private",
    "user-read-playback-state",
    "user-read-currently-playing",
    "user-modify-playback-state"
  ],
  "reminders": [
    "reminders.read",
    "reminders.write"
  ]
} as const;
export const WIDGET_PROVIDER_CONNECTORS = {
  "spotify.account": "spotify",
  "spotify.track.title": "spotify",
  "spotify.track.artist": "spotify",
  "spotify.playback.isPlaying": "spotify",
  "spotify.playback.progress": "spotify",
  "spotify.playback.volume": "spotify",
  "reminders.account": "reminders",
  "reminders.items": "reminders",
  "reminders.incompleteCount": "reminders",
  "reminders.next.title": "reminders",
  "reminders.next.dueDate": "reminders"
} as const;
export const WIDGET_ACTION_CONNECTORS = {
  "spotify.play": "spotify",
  "spotify.pause": "spotify",
  "spotify.next": "spotify",
  "spotify.previous": "spotify",
  "spotify.set-volume": "spotify",
  "reminders.create": "reminders",
  "reminders.update": "reminders",
  "reminders.complete": "reminders",
  "reminders.delete": "reminders"
} as const;
